### ISSUE TITLE
'ssl-tcp' protocol enforces the use of ssl_cert with no error handling

### ISSUE THREAD

**Issue by MakeNowJust** [logstash-plugins/logstash-output-syslog#42]
This project has just the same issue as logstash-plugins/logstash-output-tcp#22.

config:

```
input {
    stdin { }
}

output {
    syslog {
        host => "localhost"
        port => 9000
        protocol => "ssl-tcp"
        ssl_cacert => "./ca_cert.pem"
    }
}
```

output:

```
[2017-11-01T15:14:25,029][ERROR][logstash.agent           ] Pipeline aborted due to error {:exception=>#<TypeError: can't convert nil into String>, :backtrace=>["org/jruby/RubyIO.java:3804:in `read'", "org/jruby/RubyIO.java:3987:in `read'", "/usr/local/Cellar/logstash/5.6.2/libexec/vendor/bundle/jruby/1.9/gems/logstash-output-syslog-3.0.3/lib/logstash/outputs/syslog.rb:229:in `setup_ssl'", "/usr/local/Cellar/logstash/5.6.2/libexec/vendor/bundle/jruby/1.9/gems/logstash-output-syslog-3.0.3/lib/logstash/outputs/syslog.rb:132:in `register'", "org/jruby/RubyArray.java:1613:in `each'", "/usr/local/Cellar/logstash/5.6.2/libexec/logstash-core/lib/logstash/output_delegator_strategies/legacy.rb:17:in `register'", "/usr/local/Cellar/logstash/5.6.2/libexec/logstash-core/lib/logstash/output_delegator.rb:43:in `register'", "/usr/local/Cellar/logstash/5.6.2/libexec/logstash-core/lib/logstash/pipeline.rb:290:in `register_plugin'", "/usr/local/Cellar/logstash/5.6.2/libexec/logstash-core/lib/logstash/pipeline.rb:301:in `register_plugins'", "org/jruby/RubyArray.java:1613:in `each'", "/usr/local/Cellar/logstash/5.6.2/libexec/logstash-core/lib/logstash/pipeline.rb:301:in `register_plugins'", "/usr/local/Cellar/logstash/5.6.2/libexec/logstash-core/lib/logstash/pipeline.rb:310:in `start_workers'", "/usr/local/Cellar/logstash/5.6.2/libexec/logstash-core/lib/logstash/pipeline.rb:235:in `run'", "/usr/local/Cellar/logstash/5.6.2/libexec/logstash-core/lib/logstash/agent.rb:398:in `start_pipeline'"]}
```

And I think logstash-plugins/logstash-output-tcp#31 can be ported to this project to solve this issue. Thank you.

**Comment by limdauto** [comment]
Could someone merge the fix for this please? I really need it.

**Comment by willscavforlabkeys** [comment]
5 years later....

**Comment by msbart29** [comment]
I didn't understand why ssl_cert and ssl_key are required when "ssl-tcp" mode si set ...
To fix-it, I editied the syslog.rb file. (Logstash 7.17.3 - syslog output 3.0.5)
Below the patch to apply

`+++ /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-syslog-3.0.5/lib/logstash/outputs/syslog.rb      2023-04-06 15:58:56.425639990 +0200
@@ -226,8 +226,12 @@
   def setup_ssl
     require "openssl"
     ssl_context = OpenSSL::SSL::SSLContext.new
-    ssl_context.cert = OpenSSL::X509::Certificate.new(File.read(@ssl_cert))
-    ssl_context.key = OpenSSL::PKey::RSA.new(File.read(@ssl_key),@ssl_key_passphrase)
+    if @ssl_cert and File.file?(@ssl_cert)
+      ssl_context.cert = OpenSSL::X509::Certificate.new(File.read(@ssl_cert))
+    end
+    if @ssl_key and File.file?(@ssl_key)
+      ssl_context.key = OpenSSL::PKey::RSA.new(File.read(@ssl_key),@ssl_key_passphrase)
+    end
     if @ssl_verify
       cert_store = OpenSSL::X509::Store.new
       # Load the system default certificate path to the store
`

Regards
