### ISSUE TITLE
no implicit conversion of nil into String

### ISSUE THREAD

**Issue by giwery** [logstash-plugins/logstash-output-syslog#56]
When I try run logstash with next config:
```
output {
    if "security" in [message] {    
    syslog {
        host => "something.com"       
        port => 5514
        protocol => "ssl-tcp"
        ssl_cacert => "/usr/share/logstash/siemserver.pem"
        }
```
I get next error:

```
[2020-07-03T16:10:59,570][ERROR][logstash.pipeline        ] Error registering plugin {:pipeline_id=>"main", :plugin=>"#<LogStash::OutputDelegator:0x39163514>", :error=>"no implicit conversion of nil into String", :thread=>"#<Thread:0xd02579a run>"}
[2020-07-03T16:10:59,575][ERROR][logstash.pipeline        ] Pipeline aborted due to error {:pipeline_id=>"main", :exception=>#<TypeError: no implicit conversion of nil into String>, :backtrace=>["org/jruby/RubyIO.java:3770:in `read'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-syslog-3.0.5/lib/logstash/outputs/syslog.rb:230:in `setup_ssl'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-syslog-3.0.5/lib/logstash/outputs/syslog.rb:132:in `register'", "org/logstash/config/ir/compiler/OutputStrategyExt.java:106:in `register'", "org/logstash/config/ir/compiler/AbstractOutputDelegatorExt.java:48:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:259:in `register_plugin'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:270:in `block in register_plugins'", "org/jruby/RubyArray.java:1792:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:270:in `register_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:611:in `maybe_setup_out_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:280:in `start_workers'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:217:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:176:in `block in start'"], :thread=>"#<Thread:0xd02579a run>"}
[2020-07-03T16:10:59,600][ERROR][logstash.agent           ] Failed to execute action {:id=>:main, :action_type=>LogStash::ConvergeResult::FailedAction, :message=>"Could not execute action: PipelineAction::Create<main>, action_result: false", :backtrace=>nil}
[2020-07-03T16:10:59,961][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2020-07-03T16:11:04,861][INFO ][logstash.runner          ] Logstash shut down.
```

I tried the same config with tcp plugin and it works.

**Comment by parkertim** [comment]
I have the same issue and so far all I have found is that if I remove the "ssl-tcp" protocol I no longer get the error. It seems like it doesn't like that particular setting. I think udp and tcp work though.

**Comment by p3l1** [comment]
Problem is still present to this day.

To prevent this from happening just set the `ssl_cert` variable to a valid path, where a self-signed certificate is located. Then everything is working just fine for me.
